In [1]:
import pandas as pd


df = pd.read_csv('files/weather_data.csv')
print(pd.io.sql.get_schema(df, name='weather_data'))

CREATE TABLE "weather_data" (
"ghi" INTEGER,
  "dhi" INTEGER,
  "precip" REAL,
  "timestamp_utc" TEXT,
  "temp" REAL,
  "app_temp" REAL,
  "dni" INTEGER,
  "snow_depth" INTEGER,
  "wind_cdir" TEXT,
  "rh" INTEGER,
  "pod" TEXT,
  "pop" INTEGER,
  "ozone" INTEGER,
  "clouds_hi" INTEGER,
  "clouds" INTEGER,
  "vis" REAL,
  "wind_spd" REAL,
  "wind_cdir_full" TEXT,
  "slp" INTEGER,
  "datetime" TEXT,
  "ts" INTEGER,
  "pres" INTEGER,
  "dewpt" REAL,
  "uv" INTEGER,
  "clouds_mid" INTEGER,
  "wind_dir" INTEGER,
  "snow" INTEGER,
  "clouds_low" INTEGER,
  "solar_rad" REAL,
  "wind_gust_spd" REAL,
  "timestamp_local" TEXT,
  "description(output)" TEXT,
  "code" INTEGER,
  "icon" TEXT
)

In [3]:
df.head()

,ghi,dhi,precip,timestamp_utc,temp,app_temp,dni,snow_depth,wind_cdir,rh,...,clouds_mid,wind_dir,snow,clouds_low,solar_rad,wind_gust_spd,timestamp_local,description(output),code,icon
0,0,0,0.0,2025-01-15T12:00:00,25.9,18.7,0,0,NNW,51,...,0,350,0,0,0.00000,11.9,2025-01-15T07:00:00,Few clouds,801,c02n
1,385,87,0.0,2025-01-15T15:00:00,29.3,22.8,748,0,NNW,41,...,0,360,0,0,384.62994,11.9,2025-01-15T10:00:00,Clear Sky,800,c01d
2,542,101,0.0,2025-01-15T18:00:00,36.5,32.0,831,0,NNW,30,...,0,340,0,0,542.37920,9.6,2025-01-15T13:00:00,Few clouds,801,c02d
3,193,65,0.0,2025-01-15T21:00:00,38.3,35.6,581,0,NW,28,...,0,310,0,0,192.98000,6.9,2025-01-15T16:00:00,Clear Sky,800,c01d
4,0,0,0.0,2025-01-16T00:00:00,29.3,27.5,0,0,W,46,...,0,280,0,0,0.00000,2.0,2025-01-15T19:00:00,Few clouds,801,c02n

In [5]:
df.describe()

,ghi,dhi,precip,temp,app_temp,dni,snow_depth,rh,pop,ozone,...,pres,dewpt,uv,clouds_mid,wind_dir,snow,clouds_low,solar_rad,wind_gust_spd,code
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.0,40.000000,40.000000,40.000000,...,40.000000,40.000000,40.00000,40.000000,40.000000,40.0,40.00000,40.000000,40.000000,40.00000
mean,142.300000,31.875000,0.003625,37.200000,35.140000,271.675000,0.0,69.800000,7.625000,318.750000,...,1011.825000,27.137500,0.70000,24.975000,265.875000,0.0,30.37500,114.497583,8.070000,769.80000
std,206.094477,42.657363,0.008548,7.995223,9.249665,360.709656,0.0,21.294275,15.441681,21.042996,...,5.848022,11.898517,1.01779,40.780518,63.467006,0.0,42.95059,175.889617,3.618202,117.68258
min,0.000000,0.000000,0.000000,21.900000,18.700000,0.000000,0.0,28.000000,0.000000,292.000000,...,1003.000000,8.100000,0.00000,0.000000,160.000000,0.0,0.00000,0.000000,1.100000,301.00000
25%,0.000000,0.000000,0.000000,31.450000,27.450000,0.000000,0.0,54.750000,0.000000,303.750000,...,1006.750000,18.450000,0.00000,0.000000,210.000000,0.0,0.00000,0.000000,5.800000,801.00000
50%,0.000000,0.000000,0.000000,37.600000,34.700000,0.000000,0.0,75.500000,0.000000,311.500000,...,1013.000000,27.300000,0.00000,0.000000,265.000000,0.0,0.00000,0.000000,8.300000,801.00000
75%,251.500000,72.000000,0.000000,44.175000,42.850000,635.500000,0.0,84.500000,0.000000,332.500000,...,1016.000000,38.650000,1.25000,40.750000,330.000000,0.0,71.25000,193.830832,10.800000,803.00000
max,557.000000,102.000000,0.040000,50.200000,50.200000,836.000000,0.0,100.000000,55.000000,371.000000,...,1023.000000,45.300000,3.00000,100.000000,360.000000,0.0,100.00000,549.339200,15.700000,804.00000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ghi                  40 non-null     int64
 1   dhi                  40 non-null     int64
 2   precip               40 non-null     float64
 3   timestamp_utc        40 non-null     object
 4   temp                 40 non-null     float64
 5   app_temp             40 non-null     float64
 6   dni                  40 non-null     int64
 7   snow_depth           40 non-null     int64
 8   wind_cdir            40 non-null     object
 9   rh                   40 non-null     int64
 10  pod                  40 non-null     object
 11  pop                  40 non-null     int64
 12  ozone                40 non-null     int64
 13  clouds_hi            40 non-null     int64
 14  clouds               40 non-null     int64
 15  vis                  40 non-null     float64
 16  wind_spd             40 non-null     float64
 17  wind_cdir_full       40 non-null     object
 18  slp                  40 non-null     int64
 19  datetime             40 non-null     object
 20  ts                   40 non-null     int64
 21  pres                 40 non-null     int64
 22  dewpt                40 non-null     float64
 23  uv                   40 non-null     int64
 24  clouds_mid           40 non-null     int64
 25  wind_dir             40 non-null     int64
 26  snow                 40 non-null     int64
 27  clouds_low           40 non-null     int64
 28  solar_rad            40 non-null     float64
 29  wind_gust_spd        40 non-null     float64
 30  timestamp_local      40 non-null     object
 31  description(output)  40 non-null     object
 32  code                 40 non-null     int64
 33  icon                 40 non-null     object
dtypes: float64(8), int64(18), object(8)
memory usage: 10.8+ KB

In [11]:
df.columns

Index(['ghi', 'dhi', 'precip', 'timestamp_utc', 'temp', 'app_temp', 'dni',
       'snow_depth', 'wind_cdir', 'rh', 'pod', 'pop', 'ozone', 'clouds_hi',
       'clouds', 'vis', 'wind_spd', 'wind_cdir_full', 'slp', 'datetime', 'ts',
       'pres', 'dewpt', 'uv', 'clouds_mid', 'wind_dir', 'snow', 'clouds_low',
       'solar_rad', 'wind_gust_spd', 'timestamp_local', 'description(output)',
       'code', 'icon'],
      dtype='object')